package day59_Multiple_Exception;

public class throw_Keyword {
	
	public static void main(String[] args) {
		RuntimeException obj = new RuntimeException();
		
		//throw obj;
		
		//throw new RuntimeException();
		
		//System.out.println("Test completed");
		
		//throw new IOException();
		
		
		
	}

}
